version: '3.8'

services:
  app:
    container_name: img_stack_app
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        user: ${USER}
        uid: ${UID}
        gid: ${GID}
    working_dir: /var/www/html
    networks:
      - img_stack_network
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/local/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  node:
    image: node:latest
    container_name: img_stack_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - img_stack_network
    depends_on:
      - app
    tty: true
    stdin_open: true
    command: >
      /bin/sh -c "npm install -g serverless@3.39.0 && tail -f /dev/null"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_DEFAULT_REGION}

networks:
  img_stack_network:
    driver: bridge
